#!/usr/bin/env python3
"""Generate app-product/httpdbaga/hpack_tables.baga from RFC 7541 text.

Usage:
    python3 gen_hpack_tables.py /path/to/rfc7541.txt [out.baga]

Fetch the RFC once with:
    curl -sL https://www.rfc-editor.org/rfc/rfc7541.txt -o /tmp/rfc7541.txt

Appendix A -> HPACK static table (61 entries)
Appendix B -> Huffman code (256 symbols + EOS), arranged for canonical decoding.

Validates the parse: entry counts, canonical-code invariants, spot checks.
"""
import os, re, sys

if len(sys.argv) < 2:
    sys.exit("usage: gen_hpack_tables.py /path/to/rfc7541.txt [out.baga]")
RFC = sys.argv[1]
OUT = sys.argv[2] if len(sys.argv) > 2 else os.path.join(
    os.path.dirname(os.path.abspath(__file__)), "hpack_tables.baga")

text = open(RFC, encoding="utf-8").read()

# ---------- Appendix A: static table ----------
static = []
for m in re.finditer(r"\|\s*(\d+)\s*\|\s*([a-z:-]+)\s*\|\s*([^|]*?)\s*\|", text):
    idx = int(m.group(1))
    if 1 <= idx <= 61:
        static.append((idx, m.group(2), m.group(3)))
static = sorted(set(static), key=lambda t: t[0])
assert len(static) == 61, f"static table: {len(static)} entries"
assert [e[0] for e in static] == list(range(1, 62))
by_idx = {i: (n, v) for i, n, v in static}
assert by_idx[2] == (":method", "GET")
assert by_idx[3] == (":method", "POST")
assert by_idx[4] == (":path", "/")
assert by_idx[8] == (":status", "200")
assert by_idx[16] == ("accept-encoding", "gzip, deflate")
assert by_idx[31] == ("content-type", "")
assert by_idx[38] == ("host", "")

# ---------- Appendix B: Huffman table ----------
huff = []  # (sym, code, bits); sym 256 == EOS
app_b = text.split("Appendix B.  Huffman Code")[1]
for m in re.finditer(r"\(\s*(\d+|EOS)\s*\)\s+\|.*?([0-9a-f]+)\s+\[\s*(\d+)\]", app_b):
    s = m.group(1)
    sym = 256 if s == "EOS" else int(s)
    code = int(m.group(2), 16)
    bits = int(m.group(3))
    huff.append((sym, code, bits))
assert len(huff) == 257, f"huffman: {len(huff)} entries"
assert len({s for s, _, _ in huff}) == 257
# spot check from RFC body: symbol 47 ('/') = 0x18 in 6 bits
assert (47, 0x18, 6) in huff, "RFC example: '/' = 0x18 [6]"
# EOS is 30 bits of all-ones
eos = next((c, b) for s, c, b in huff if s == 256)
assert eos == ((1 << 30) - 1, 30), f"EOS wrong: {eos}"

# canonical check: sort by (bits, sym); codes must be consecutive per length
# and first code of next length = (last+1) << delta
ordered = sorted(huff, key=lambda t: (t[2], t[0]))
prev_bits, prev_code = None, None
for sym, code, bits in ordered:
    if prev_bits is None:
        pass
    elif bits == prev_bits:
        assert code == prev_code + 1, f"non-consecutive at sym {sym}"
    else:
        assert code == (prev_code + 1) << (bits - prev_bits), f"canonical jump broken at sym {sym}"
    prev_bits, prev_code = bits, code
print("canonical Huffman invariants: OK", file=sys.stderr)

# per-length decode arrays: entries sorted by (bits, code) == (bits, sym) here
by_sym = {s: (c, b) for s, c, b in huff}
lengths = sorted({b for _, _, b in huff})
first_code, first_off, count = {}, {}, {}
pos = 0
for LL in lengths:
    grp = [(s, c) for s, c, b in huff if b == LL]
    grp.sort(key=lambda t: t[1])
    first_code[LL], first_off[LL], count[LL] = grp[0][1], pos, len(grp)
    pos += len(grp)
flat_syms = [t[0] for t in sorted(huff, key=lambda t: (t[2], t[1]))]

# encoder side: per-symbol code/bits (sym order 0..256)
enc_code = [by_sym[s][0] for s in range(257)]
enc_bits = [by_sym[s][1] for s in range(257)]

# ---------- emit Baga ----------
L = []
w = L.append
w("// hpack_tables.baga — GENERATED by gen_hpack_tables.py from RFC 7541")
w("// (Appendix A static table, Appendix B Huffman code). Do not edit by hand.")
w("// Canonical-code invariants checked at generation time.")
w("")
w("// ---------- Appendix A: static table (indices 1..61) ----------")
w("")
w("fn hpack_static_len() -> i64 {")
w("    return 61")
w("}")
w("")
w("fn hpack_static_name(i: i64) -> str {")
for i, n, v in static:
    w(f"    if i == {i} {{ return \"{n}\" }}")
w("    return \"\"")
w("}")
w("")
w("fn hpack_static_value(i: i64) -> str {")
for i, n, v in static:
    if v:
        w(f"    if i == {i} {{ return \"{v}\" }}")
w("    return \"\"")
w("}")
w("")
w("// ---------- Appendix B: Huffman ----------")
w("")
w("// Encode side: code (LSB-aligned) and bit length per symbol 0..256 (256 = EOS).")
w("")
w("fn huff_enc_code(sym: i64) -> i64 {")
for s in range(257):
    w(f"    if sym == {s} {{ return {enc_code[s]} }}")
w("    return 0")
w("}")
w("")
w("fn huff_enc_bits(sym: i64) -> i64 {")
runs = []
i = 0
while i < 257:
    j = i
    while j + 1 < 257 and enc_bits[j + 1] == enc_bits[i]:
        j += 1
    runs.append((i, j, enc_bits[i]))
    i = j + 1
for lo, hi, b in runs:
    if lo == hi:
        w(f"    if sym == {lo} {{ return {b} }}")
    else:
        w(f"    if sym >= {lo} && sym <= {hi} {{ return {b} }}")
w("    return 0")
w("}")
w("")
w("// Decode side: entries sorted by (bits, code). For bit length L,")
w("// symbols occupy flat positions first_off[L] .. first_off[L]+count[L)-1")
w("// and codes run consecutively from first_code[L].")
w("")
w("fn huff_max_bits() -> i64 {")
w(f"    return {max(lengths)}")
w("}")
w("")
w("fn huff_first_code(bitslen: i64) -> i64 {")
for LL in lengths:
    w(f"    if bitslen == {LL} {{ return {first_code[LL]} }}")
w("    return -1")
w("}")
w("")
w("fn huff_first_off(bitslen: i64) -> i64 {")
for LL in lengths:
    w(f"    if bitslen == {LL} {{ return {first_off[LL]} }}")
w("    return -1")
w("}")
w("")
w("fn huff_count_at(bitslen: i64) -> i64 {")
for LL in lengths:
    w(f"    if bitslen == {LL} {{ return {count[LL]} }}")
w("    return 0")
w("}")
w("")
w("fn huff_flat_sym(idx: i64) -> i64 {")
for k, s in enumerate(flat_syms):
    w(f"    if idx == {k} {{ return {s} }}")
w("    return 256")
w("}")
w("")
open(OUT, "w", encoding="utf-8").write("\n".join(L))
print(f"wrote {OUT}: {len(L)} lines", file=sys.stderr)
