[package]
name = "reportbaga"
version = "0.3.1"
entry = "report.baga"

[dependencies]
std = { path = "../../std" }
csvbaga = { path = "../csvbaga" }
officebaga = { path = "../officebaga" }
pdfbaga = { path = "../pdfbaga" }
xmlbaga = { path = "../xmlbaga" }
bufbaga = { path = "../bufbaga" }
tplbaga = { path = "../tplbaga" }
