[package]
name = "cloudbaga"
version = "0.1.0"
entry = "app.baga"

[dependencies]
httpdbaga = { path = "../httpdbaga" }
metbaga = { path = "../metbaga" }
logbaga = { path = "../logbaga" }
otelbaga = { path = "../otelbaga" }
pbbaga = { path = "../pbbaga" }
std = { path = "../../std" }
