[package]
name = "oauthbaga"
version = "0.2.0"
entry = "server.baga"

[dependencies]
std = { path = "../../std" }
httpdbaga = { path = "../httpdbaga" }
jwtbaga = { path = "../jwtbaga" }
tplbaga = { path = "../tplbaga" }
ormbaga = { path = "../ormbaga" }
pgbaga = { path = "../pgbaga" }
